// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCgBOhzIwdHIE8OBebGbrymz5rxptm75bo",
  authDomain: "pizza-hot-app.firebaseapp.com",
  projectId: "pizza-hot-app",
  storageBucket: "pizza-hot-app.firebasestorage.app",
  messagingSenderId: "1009165157580",
  appId: "1:1009165157580:web:c9628943d973ddcf75ae69"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSd7D0zU6JmH_OENDR0ir-TIgzBAp-e1w',
    appId: '1:1009165157580:android:557888a4df8045ff75ae69',
    messagingSenderId: '1009165157580',
    projectId: 'pizza-hot-app',
    storageBucket: 'pizza-hot-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWiu5iBUEXbH2bnnbKiv5cw_FYnnLkFY',
    appId: '1:703166424327:ios:4f452dae1eddaff066d1a2',
    messagingSenderId: '703166424327',
    projectId: 'food-delivery-applicatio-39ecd',
    storageBucket: 'food-delivery-applicatio-39ecd.appspot.com',
    iosBundleId: 'com.example.foodOrder',
  );
}
